---
format: 
    pdf:
        template: resume_template.tex
        font: Open Sans
        number-sections: false
name: Morgan Squire, ACAS
# title: Data Scientist
summary: Innovative Data Scientist and Actuary with six years of experience modernizing and automating analytical processes. Passionate about implementing software development best practices into model development.
contact:
    location: Riverview, FL
    phone: (555) 555-5555
    email: first.last@domain.com
portfolio:
    linkedin: \href{https://www.linkedin.com/in/yournamehere/}{yournamehere}
    github: \href{https://github.com/mosquire}{mosquire}
skills:
    - Languages:
        - Python
        - R
        - SQL
        - Latex
    - Development Tools:
        - Git
        - VSCode
        - RStudio
        - JupyterLab
        - Conda
    - Statistical Modeling:
        - Generalized Linear Modeling
        - Generalized Additive Modeling
        - Downsampling/Upweighting
        - Regularization
        - Tree-Based Machine Learning
    - Data:
        - Hive
        - Parquet
        - Snowflake
        - Partitioning
        - JSON
    - Package Development:
        - Unit Testing
        - Docstrings/Roxygen
        - Logging
        - Debugging
        - Markdown
---
# Experience

## USAA: 2016 - Present

### Associate Actuary, 2020 - Present:

* Overhauled the Homeowners loss models to incorporate claim type into claim surcharges to reduce subsidy
* Led a team of 4 in the development of an internal Python package using H2O and scikit-learn
* Reduced model fit times by 50% by implementing a model pipeline cache
* Mentored Data Scientists and Actuaries on Python package development to include unit testing, documentation, website publishing, logging, debugging, and git branching strategies.
* Designed and delivered 6 hours of interactive training for a team of 12 model developers including a tutorial Git repository that covered Python, Git, H2O and an internal model development Python package
* Established 14 virtual machines to enable a team of model developers to fit models on a 40 GB dataset in H2O
* Presented complex technical improvements to executive leadership on multiple occasions

### Actuarial Analyst, 2017 - 2020:

* Developed an advanced process for territorial smoothing using thin-plate splines in a Generalized Additive Model in R
* Coordinated with the Texas Department of Insurance to secure approval of a new capital allocation strategy
* Designed and published an internal R package with tools for connecting to company databases and estimating within-class and between-class variance
* Trained the modeling community of practice on R package development tailored to internal systems
* Optimized deductible rating factors using R to calculate granular loss elimination ratios which enabled the rollout of new deductible options
* Filed rate changes in Homeowners, Renters, and Rental Property lines of business in several states

### Actuarial Modeling Intern, 2016:

* Adjusted the countrywide Homeowners model to meet state-specific requirements
* Designed an Excel VBA program to automatically generate model performance plots from model outputs.

# Education

### Bachelor of Science in Applied Mathematics: December 2016

University of Evansville, Summa Cum Laude

# Credentials

### Associate of the Casualty Actuarial Society: 2019